### ISSUE TITLE
ERROR: Service 'prestashop' failed to build:

### ISSUE THREAD

**Issue by quentinburley** [devnix/prestashop-docker-compose#1]
docker-compose build prestashop
Building prestashop
Step 1/4 : FROM prestashop/prestashop:latest
 ---> c08b977116fd
Step 2/4 : RUN yes | pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_connect_back=on" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "file_uploads=On" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "memory_limit=128M" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "upload_max_filesize=64M" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "post_max_size=64M" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "max_execution_time=600" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "max_input_vars=10000" >> /usr/local/etc/php/conf.d/custom.ini     && echo "error_reporting-1" >> /usr/local/etc/php/conf.d/custom.ini     && echo "display_errors = On" >> /usr/local/etc/php/conf.d/custom.ini
 ---> Running in 48d1236a0587
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
pecl/xdebug requires PHP (version >= 7.0.0), installed version is 5.6.33
No valid packages found
install failed
ERROR: Service 'prestashop' failed to build: The command '/bin/sh -c yes | pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_connect_back=on" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "file_uploads=On" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "memory_limit=128M" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "upload_max_filesize=64M" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "post_max_size=64M" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "max_execution_time=600" >> /usr/local/etc/php/conf.d/uploads.ini     && echo "max_input_vars=10000" >> /usr/local/etc/php/conf.d/custom.ini     && echo "error_reporting-1" >> /usr/local/etc/php/conf.d/custom.ini     && echo "display_errors = On" >> /usr/local/etc/php/conf.d/custom.ini' returned a non-zero code: 1

**Comment by devnix** [comment]
We should check this out, seems like it's related to xdebug and the PHP version from the parent image.

**Comment by mardon** [comment]
I have same problem, i try use in prestashop dockerfile 
`pecl install xdebug-2.5.5`
and it seems to be ok

**Comment by devnix** [comment]
Could you please check if the PR #2 works for you @quentinburley?

**Comment by nkoporec** [comment]
@DevNIX Your PR request is not working.It should just add xdebug-2.5.5(instead of xdebug) on the top  and delete your added row (+RUN pecl install xdebug-2.5.5).

**Comment by devnix** [comment]
I've finally tested the PR and we can mark this issue as solved. Thank you all!
